name: Pelican publish

on:
  push:
    branches:
      - content

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install deps
        run: pip install -e .
      - name: Build pelican site
        run: pelican content -o output -s pelicanconf.py
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

permissions:
  pages: write
  id-token: write
